name: pokedex
description: Pokedex Moonshot Challenge.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  dart_ping: ^9.0.0
  equatable: 2.0.5
  faker: 2.1.0
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_riverpod: 2.3.6
  get_it: ^7.6.0
  go_router: ^10.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  riverpod_annotation: ^2.1.1
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.5
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter
  hive_generator: ^2.0.0
  patrol: ^2.2.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2


flutter: 
  assets: 
    - assets/images/
  uses-material-design: true
  generate: true

fonts:
    - family: Pokemon Solid
      fonts:
        - asset: assets/fonts/pokemon/Pokemon-Solid.ttf
    - family: Pokemon Hollow
      fonts:
        - asset: assets/fonts/pokemon/Pokemon-Hollow.ttf

