name: PR checks

on:
  workflow_call:
  push:
    # branches-ignore:
      # - "develop" # Will match all branches except develop.
        # all-*-deploy.yml will call this workflow via workflow_call.

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.2"
          channel: stable

      - run: flutter --version

      # Install dependencies
      - run: flutter pub get

      # check for issues with formatting
      - run: dart format --line-length=80 --set-exit-if-changed .

      # Add env file
      - run: |
          touch assets/env
          echo 'FIREBASE_API_KEY = ${{ secrets.FIREBASE_API_KEY }}' > assets/env
          cat assets/env

      # check for issues through static analysis
      - run: flutter analyze

      # Run tests
      - run: flutter test
